AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Glue ETL Jobs for Bankruptcy Prediction - 80% reduction in manual processing time'

Parameters:
  ProjectName:
    Type: String
    Default: bankruptcy-prediction
  
  Environment:
    Type: String
    Default: prod
  
  DataLakeBucket:
    Type: String
    Description: S3 bucket for data lake
  
  ScriptBucket:
    Type: String
    Description: S3 bucket containing Glue scripts

Resources:
  # IAM Role for Glue Jobs
  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-glue-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub 'arn:aws:s3:::${DataLakeBucket}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${DataLakeBucket}'
        - PolicyName: RedshiftAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - redshift:DescribeClusters
                  - redshift:GetClusterCredentials
                Resource: '*'
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws-glue/*'

  # Glue Database
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub '${ProjectName}_${Environment}'
        Description: Database for bankruptcy prediction pipeline

  # Glue Crawler for Raw Data
  RawDataCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub '${ProjectName}-raw-data-crawler-${Environment}'
      Role: !GetAtt GlueServiceRole.Arn
      DatabaseName: !Ref GlueDatabase
      Targets:
        S3Targets:
          - Path: !Sub 's3://${DataLakeBucket}/raw/'
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Schedule:
        ScheduleExpression: 'cron(0 2 * * ? *)'  # Run daily at 2 AM

  # Main ETL Job
  BankruptcyETLJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub '${ProjectName}-etl-job-${Environment}'
      Role: !GetAtt GlueServiceRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: !Sub 's3://${ScriptBucket}/glue/etl_job.py'
        PythonVersion: '3'
      DefaultArguments:
        '--job-language': 'python'
        '--job-bookmark-option': 'job-bookmark-enable'
        '--enable-metrics': 'true'
        '--enable-continuous-cloudwatch-log': 'true'
        '--S3_INPUT_PATH': !Sub 's3://${DataLakeBucket}/raw/'
        '--S3_OUTPUT_PATH': !Sub 's3://${DataLakeBucket}/processed/'
        '--TempDir': !Sub 's3://${DataLakeBucket}/temp/'
      ExecutionProperty:
        MaxConcurrentRuns: 2
      MaxRetries: 1
      Timeout: 120
      GlueVersion: '4.0'
      NumberOfWorkers: 10
      WorkerType: G.1X
      Tags:
        Project: !Ref ProjectName
        Environment: !Ref Environment

  # Data Quality Job
  DataQualityJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub '${ProjectName}-data-quality-job-${Environment}'
      Role: !GetAtt GlueServiceRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: !Sub 's3://${ScriptBucket}/glue/data_quality.py'
        PythonVersion: '3'
      DefaultArguments:
        '--job-language': 'python'
        '--enable-metrics': 'true'
        '--enable-continuous-cloudwatch-log': 'true'
        '--S3_INPUT_PATH': !Sub 's3://${DataLakeBucket}/processed/'
      GlueVersion: '4.0'
      NumberOfWorkers: 2
      WorkerType: G.1X

  # Workflow to orchestrate ETL
  ETLWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Name: !Sub '${ProjectName}-etl-workflow-${Environment}'
      Description: Automated ETL workflow for bankruptcy prediction

  # Trigger to start workflow
  WorkflowTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: !Sub '${ProjectName}-workflow-trigger-${Environment}'
      Type: SCHEDULED
      Schedule: 'cron(0 3 * * ? *)'  # Run daily at 3 AM
      WorkflowName: !Ref ETLWorkflow
      Actions:
        - JobName: !Ref BankruptcyETLJob

  # CloudWatch Alarm for Job Failures
  ETLJobFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-etl-job-failure-${Environment}'
      AlarmDescription: Alert when ETL job fails
      MetricName: glue.driver.aggregate.numFailedTasks
      Namespace: Glue
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching

Outputs:
  GlueServiceRoleArn:
    Description: ARN of Glue service role
    Value: !GetAtt GlueServiceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-GlueServiceRole'
  
  GlueDatabaseName:
    Description: Name of Glue database
    Value: !Ref GlueDatabase
    Export:
      Name: !Sub '${AWS::StackName}-GlueDatabase'
  
  ETLJobName:
    Description: Name of main ETL job
    Value: !Ref BankruptcyETLJob
    Export:
      Name: !Sub '${AWS::StackName}-ETLJob'
